### ISSUE TITLE
Not a real issue, just a question / suggestion?

### ISSUE THREAD

**Issue by neozeed** [andrastantos/cray-sim#5]
Running gzip on the cray is insanely slow.  Since the install is relying on rcp remsh is also availble, it's way faster to decompress on the host...

`remsh 172.16.0.1 -ljsteve gzip -dc /mnt/c/temp/unicos/unicos-2/UNICOS_exe/uex_11.gzc | cpio -idv || install_errorexit "Can't extract install media"
`

I guess the only other way to speed it up is to transfer the CD-ROM contents to a 1 gig disk partition, which would maybe help?  Not sure but running gzip on the host speeds it up so much.

Just wanted to say thanks again, this is amazing!

**Comment by andrastantos** [comment]
On Sun, 2022-12-04 at 14:03 -0800, neozeed wrote:

Thanks for the note. Indeed, gzip is very slow on the Cray (simulator).
During development, I for a while decompressed the gzip files on the
host and copied over the resulting CPIOs onto a freshly created virtual
FS. There is a utility that can write CFS file-systems included in the
distribution for exactly that purpose.

At the same time, the purpose of this simulator (at least in my
opinion) is to provide as authentic an experience as possible. So, when
I got myself to put together instructions on how to set up the system,
I wanted to re-use the original install scripts as much as possible
too.

Thanks again for checking out the simulator and your kind words!

Andras
